create or replace
PROCEDURE SearchByType
(disType IN RECORDS.DIS_TYPE%TYPE,
 c OUT SYS_REFCURSOR
 )
AS
BEGIN
  OPEN c FOR
  SELECT distinct DISASTER.NAME as Name,RECORDS.DIS_TYPE as Type 
  FROM DISASTER,RECORDS 
  WHERE DISASTER."ID" = RECORDS.RECORD_ID and RECORDS.DIS_TYPE = disType;
   
END;